### ISSUE TITLE
Bootstrap 3.0 checklist

### ISSUE THREAD

**Issue by cesidio** [diowa/icare#15]
- [ ] Navbar `pull-right`
- [ ] Navbar non-collapsable menus
- [ ] Forms label not aligned
